name: Build & Deploy embed-api

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: felixmorongeportfolio/go-api

    env:
      AWS_REGION: us-east-1
      ECR_REGISTRY: yourecrrepo.amazonaws.com
      IMAGE_NAME: "yourwhatever"-go-api
      IMAGE_TAG: latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_REGISTRY

    - name: Build & Push embed-api image
      run: |
        docker build -t $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
